# Mod info
modId=hollowcore
modName=HollowCore
modVersion=2.3.12c
mod_author=HollowHorizon
mod_group=ru.hollowhorizon
java_version=21
license=MIT

# Libs
kotlinVersion=2.2.0
koolVersion=0.18.0-0mods-SNAPSHOT

# Publishing
publish.modrinth=XMd2cJSg
publish.curseforge=906892

# Gradle args
org.gradle.jvmargs=-Xmx6096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.daemon=false
