modLoader = "javafml"
loaderVersion = "[43,)"
license = "All rights reserved"
[[mods]]
modId = "hc"
version = "${file.jarVersion}"
displayName = "HollowCore"
description = '''
'''
[[dependencies.hc]]
modId = "forge"
mandatory = true
versionRange = "[43.2.6,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.hc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"