modLoader = "javafml"
loaderVersion = "[43,)"
license = "${license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "hollowcore.png"
credits = ""
authors = "HollowHorizon"
description = '''HollowCore is a minecraft modding library by HollowHorizon. It is an easy to use and powerful library for easier creation of minecraft mods for Fabric, Forge and NeoForge.'''
[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc_version},)"
ordering = "NONE"
side = "BOTH"