modLoader = "javafml"
loaderVersion = "[47,)"
license = "${license}"
[[mods]]
modId = "hollowcore"
version = "2.0"
displayName = "HollowCore"
logoFile = "hollowcore.png"
credits = ""
authors = "HollowHorizon"
description = '''HollowCore is a minecraft modding library by HollowHorizon. It is an easy to use and powerful library for easier creation of minecraft mods for Fabric, Forge and NeoForge.'''
[[dependencies.hollowcore]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.hollowcore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"