modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"
[[mods]]
modId = "hollowcore"
version = "2.0.0"
displayName = "HollowCore"
logoFile="hollowcore.png"
credits=""
authors = "HollowHorizon"
description = '''HollowCore is a minecraft modding library by HollowHorizon. It is an easy to use and powerful library for easier creation of minecraft mods for Fabric, Forge and NeoForge.
'''
[[mixins]]
config = "hollowcore.mixins.json"
[[accessTransformers]]
file="accesstransformer.cfg"
[[dependencies.hollowcore]]
modId = "neoforge"
type="required"
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.hollowcore]]
modId = "minecraft"
type="required"
versionRange = "[1.21, 1.22)"
ordering = "NONE"
side = "BOTH"