/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Effekseer.swig;

public final class EffekseerCoreDeviceType {
  public final static EffekseerCoreDeviceType Unknown = new EffekseerCoreDeviceType("Unknown");
  public final static EffekseerCoreDeviceType OpenGL = new EffekseerCoreDeviceType("OpenGL");
  public final static EffekseerCoreDeviceType DirectX9 = new EffekseerCoreDeviceType("DirectX9");
  public final static EffekseerCoreDeviceType DirectX11 = new EffekseerCoreDeviceType("DirectX11");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EffekseerCoreDeviceType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EffekseerCoreDeviceType.class + " with value " + swigValue);
  }

  private EffekseerCoreDeviceType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EffekseerCoreDeviceType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EffekseerCoreDeviceType(String swigName, EffekseerCoreDeviceType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EffekseerCoreDeviceType[] swigValues = { Unknown, OpenGL, DirectX9, DirectX11 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

