/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Effekseer.swig;

public class EffekseerCoreJNI {
  public final static native long new_EffekseerBackendCore();
  public final static native void delete_EffekseerBackendCore(long jarg1);
  public final static native int EffekseerBackendCore_GetDevice();
  public final static native boolean EffekseerBackendCore_InitializeWithOpenGL();
  public final static native void EffekseerBackendCore_Terminate();
  public final static native long new_EffekseerEffectCore();
  public final static native void delete_EffekseerEffectCore(long jarg1);
  public final static native boolean EffekseerEffectCore_Load(long jarg1, EffekseerEffectCore jarg1_, byte[] jarg2, int jarg3, float jarg4);
  public final static native String EffekseerEffectCore_GetTexturePath(long jarg1, EffekseerEffectCore jarg1_, int jarg2, int jarg3);
  public final static native int EffekseerEffectCore_GetTextureCount(long jarg1, EffekseerEffectCore jarg1_, int jarg2);
  public final static native boolean EffekseerEffectCore_LoadTexture(long jarg1, EffekseerEffectCore jarg1_, byte[] jarg2, int jarg3, int jarg4, int jarg5);
  public final static native boolean EffekseerEffectCore_HasTextureLoaded(long jarg1, EffekseerEffectCore jarg1_, int jarg2, int jarg3);
  public final static native String EffekseerEffectCore_GetModelPath(long jarg1, EffekseerEffectCore jarg1_, int jarg2);
  public final static native int EffekseerEffectCore_GetModelCount(long jarg1, EffekseerEffectCore jarg1_);
  public final static native boolean EffekseerEffectCore_LoadModel(long jarg1, EffekseerEffectCore jarg1_, byte[] jarg2, int jarg3, int jarg4);
  public final static native boolean EffekseerEffectCore_HasModelLoaded(long jarg1, EffekseerEffectCore jarg1_, int jarg2);
  public final static native String EffekseerEffectCore_GetMaterialPath(long jarg1, EffekseerEffectCore jarg1_, int jarg2);
  public final static native int EffekseerEffectCore_GetMaterialCount(long jarg1, EffekseerEffectCore jarg1_);
  public final static native boolean EffekseerEffectCore_LoadMaterial(long jarg1, EffekseerEffectCore jarg1_, byte[] jarg2, int jarg3, int jarg4);
  public final static native String EffekseerEffectCore_GetCurvePath(long jarg1, EffekseerEffectCore jarg1_, int jarg2);
  public final static native boolean EffekseerEffectCore_HasMaterialLoaded(long jarg1, EffekseerEffectCore jarg1_, int jarg2);
  public final static native int EffekseerEffectCore_GetCurveCount(long jarg1, EffekseerEffectCore jarg1_);
  public final static native boolean EffekseerEffectCore_LoadCurve(long jarg1, EffekseerEffectCore jarg1_, byte[] jarg2, int jarg3, int jarg4);
  public final static native boolean EffekseerEffectCore_HasCurveLoaded(long jarg1, EffekseerEffectCore jarg1_, int jarg2);
  public final static native int EffekseerEffectCore_GetTermMax(long jarg1, EffekseerEffectCore jarg1_);
  public final static native int EffekseerEffectCore_GetTermMin(long jarg1, EffekseerEffectCore jarg1_);
  public final static native long new_EffekseerManagerCore();
  public final static native void delete_EffekseerManagerCore(long jarg1);
  public final static native boolean EffekseerManagerCore_Initialize__SWIG_0(long jarg1, EffekseerManagerCore jarg1_, int jarg2, boolean jarg3);
  public final static native boolean EffekseerManagerCore_Initialize__SWIG_1(long jarg1, EffekseerManagerCore jarg1_, int jarg2);
  public final static native void EffekseerManagerCore_Update(long jarg1, EffekseerManagerCore jarg1_, float jarg2);
  public final static native void EffekseerManagerCore_BeginUpdate(long jarg1, EffekseerManagerCore jarg1_);
  public final static native void EffekseerManagerCore_EndUpdate(long jarg1, EffekseerManagerCore jarg1_);
  public final static native void EffekseerManagerCore_UpdateHandleToMoveToFrame(long jarg1, EffekseerManagerCore jarg1_, int jarg2, float jarg3);
  public final static native int EffekseerManagerCore_Play(long jarg1, EffekseerManagerCore jarg1_, long jarg2, EffekseerEffectCore jarg2_);
  public final static native void EffekseerManagerCore_StopAllEffects(long jarg1, EffekseerManagerCore jarg1_);
  public final static native void EffekseerManagerCore_Stop(long jarg1, EffekseerManagerCore jarg1_, int jarg2);
  public final static native void EffekseerManagerCore_SetPaused(long jarg1, EffekseerManagerCore jarg1_, int jarg2, boolean jarg3);
  public final static native void EffekseerManagerCore_SetShown(long jarg1, EffekseerManagerCore jarg1_, int jarg2, boolean jarg3);
  public final static native void EffekseerManagerCore_SendTrigger(long jarg1, EffekseerManagerCore jarg1_, int jarg2, int jarg3);
  public final static native void EffekseerManagerCore_SetEffectPosition(long jarg1, EffekseerManagerCore jarg1_, int jarg2, float jarg3, float jarg4, float jarg5);
  public final static native void EffekseerManagerCore_SetEffectRotation(long jarg1, EffekseerManagerCore jarg1_, int jarg2, float jarg3, float jarg4, float jarg5);
  public final static native void EffekseerManagerCore_SetEffectScale(long jarg1, EffekseerManagerCore jarg1_, int jarg2, float jarg3, float jarg4, float jarg5);
  public final static native void EffekseerManagerCore_SetLayerParameter(long jarg1, EffekseerManagerCore jarg1_, int jarg2, float jarg3, float jarg4, float jarg5, float jarg6);
  public final static native void EffekseerManagerCore_SetEffectTransformMatrix(long jarg1, EffekseerManagerCore jarg1_, int jarg2, float jarg3, float jarg4, float jarg5, float jarg6, float jarg7, float jarg8, float jarg9, float jarg10, float jarg11, float jarg12, float jarg13, float jarg14);
  public final static native void EffekseerManagerCore_SetEffectTransformBaseMatrix(long jarg1, EffekseerManagerCore jarg1_, int jarg2, float jarg3, float jarg4, float jarg5, float jarg6, float jarg7, float jarg8, float jarg9, float jarg10, float jarg11, float jarg12, float jarg13, float jarg14);
  public final static native void EffekseerManagerCore_DrawBack__SWIG_0(long jarg1, EffekseerManagerCore jarg1_, int jarg2);
  public final static native void EffekseerManagerCore_DrawBack__SWIG_1(long jarg1, EffekseerManagerCore jarg1_);
  public final static native void EffekseerManagerCore_DrawFront__SWIG_0(long jarg1, EffekseerManagerCore jarg1_, int jarg2);
  public final static native void EffekseerManagerCore_DrawFront__SWIG_1(long jarg1, EffekseerManagerCore jarg1_);
  public final static native void EffekseerManagerCore_SetLayer(long jarg1, EffekseerManagerCore jarg1_, int jarg2, int jarg3);
  public final static native void EffekseerManagerCore_SetCameraParameter(long jarg1, EffekseerManagerCore jarg1_, float jarg2, float jarg3, float jarg4, float jarg5, float jarg6, float jarg7);
  public final static native void EffekseerManagerCore_SetProjectionMatrix(long jarg1, EffekseerManagerCore jarg1_, float jarg2, float jarg3, float jarg4, float jarg5, float jarg6, float jarg7, float jarg8, float jarg9, float jarg10, float jarg11, float jarg12, float jarg13, float jarg14, float jarg15, float jarg16, float jarg17);
  public final static native void EffekseerManagerCore_SetCameraMatrix(long jarg1, EffekseerManagerCore jarg1_, float jarg2, float jarg3, float jarg4, float jarg5, float jarg6, float jarg7, float jarg8, float jarg9, float jarg10, float jarg11, float jarg12, float jarg13, float jarg14, float jarg15, float jarg16, float jarg17);
  public final static native boolean EffekseerManagerCore_Exists(long jarg1, EffekseerManagerCore jarg1_, int jarg2);
  public final static native void EffekseerManagerCore_SetViewProjectionMatrixWithSimpleWindow(long jarg1, EffekseerManagerCore jarg1_, int jarg2, int jarg3);
  public final static native void EffekseerManagerCore_SetDynamicInput(long jarg1, EffekseerManagerCore jarg1_, int jarg2, int jarg3, float jarg4);
  public final static native float EffekseerManagerCore_GetDynamicInput(long jarg1, EffekseerManagerCore jarg1_, int jarg2, int jarg3);
  public final static native void EffekseerManagerCore_LaunchWorkerThreads(long jarg1, EffekseerManagerCore jarg1_, int jarg2);
  public final static native void EffekseerManagerCore_SetBackground(long jarg1, EffekseerManagerCore jarg1_, long jarg2, boolean jarg3);
  public final static native void EffekseerManagerCore_UnsetBackground(long jarg1, EffekseerManagerCore jarg1_);
  public final static native void EffekseerManagerCore_SetDepth(long jarg1, EffekseerManagerCore jarg1_, long jarg2, boolean jarg3);
  public final static native void EffekseerManagerCore_UnsetDepth(long jarg1, EffekseerManagerCore jarg1_);
  public final static native int EffekseerManagerCore_GetInstanceCount(long jarg1, EffekseerManagerCore jarg1_, int jarg2);
  public final static native int EffekseerManagerCore_GetTotalInstanceCount(long jarg1, EffekseerManagerCore jarg1_);
}
