name: build
on: 
  push:
    branches: [ "stonecutter" ]
  pull_request:
    branches: [ "stonecutter" ]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [21] 
        os: [ubuntu-20.04, self-hosted]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew chiseledBuildAndCollect
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }}
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
      - name: automatic upload
        uses: marvinpinto/action-automatic-releases@latest
        with: 
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-1.21"
          prerelease: false
          title: "[AUTOMATIC BUILD]"
          files: |
            build/libs/1.19.2/*.jar
            build/libs/1.20.1/*.jar
            build/libs/1.21/*.jar
