name: build
on: 
  push:
    branches: [ "stonecutter" ]
  pull_request:
    branches: [ "stonecutter" ]

jobs:
  build:
    strategy:
      matrix:
        java: [21] 
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    if: |
      !contains(github.event.head_commit.message, '[no ci]')
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Release to GitHub
        uses: gradle/gradle-build-action@v2
        with:
          arguments: chiseledBuildAndCollect
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }}
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            merged/*.jar
            !merged/*-dev.jar
            !merged/*-sources.jar
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: "[MULTI-VERSIONED BUILD]"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          artifacts: "merged/*.jar"
          artifactContentType: application/java-archive