name: build
on: 
  push:
    branches: [ "stonecutter" ]
  pull_request:
    branches: [ "stonecutter" ]
  workflow_dispatch:
    inputs:
      no-build:
        description: 'Do not compile & publish'
        required: true
        default: 'false'
      no-actions:
        description: 'Do not any actions'
        required: true
        default: 'false'

jobs:
  build:
    strategy:
      matrix:
        java: [21] 
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Release to GitHub
        uses: gradle/gradle-build-action@v2
        if: |
          (!contains(github.event.head_commit, '[no-build]') || github.event.inputs.no-build != 'true') || (!contains(github.event.head_commit, '[no-actions]') || github.event.inputs.no-actions != 'true')
        with:
          arguments: chiseledBuildAndCollect
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }}
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
      - name: automatic upload
        uses: marvinpinto/action-automatic-releases@latest
        with: 
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "[MULTI-VERSIONED BUILD]"
          files: |
            build/libs/1.19.2/*.jar
            build/libs/1.20.1/*.jar
            build/libs/1.21/*.jar
