name: mavenPublish
on:
  push:
    branches: [ "1.20.1" ]

jobs:
  build:
    strategy:
      matrix:
        java: [21]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    if: |
      !contains(github.event.head_commit.message, '[no ci]')
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        if: |
          !contains(github.event.head_commit.message, '[no maven]')
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Release to Maven
        uses: gradle/gradle-build-action@v2
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        with:
          arguments: chiseledPublishMaven
